name: Build and Push Docker Image

on:
  push:
    branches:
      - r1.6.1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
    
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Aliyun Docker Registry
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.ALIYUN_REGISTRY_USERNAME }}"
        password: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

    - name: Build and push image
      run: |
        docker build -f Dockerfile.builder -t registry.cn-hangzhou.aliyuncs.com/yourui/deepvariant_gpu_builder:latest .
        docker push registry.cn-hangzhou.aliyuncs.com/yourui/deepvariant_gpu_builder:latest
