name: Build and Push Docker Image

on:
  push:
    branches:
      - r1.6.1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Aliyun Docker Registry
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.ALIYUN_REGISTRY_USERNAME }}"
        password: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

    - name: Build and push image
      run: |
        docker build -f Dockerfile --target builder -t registry.cn-hangzhou.aliyuncs.com/yourui/deepvariant_builder:latest .
        docker push registry.cn-hangzhou.aliyuncs.com/yourui/deepvariant_builder:latest
